### ISSUE TITLE
eos_bgp_* modules take a long time to complete

### ISSUE THREAD

**Issue by perimore** [arista-eosplus/ansible-eos#59]

**Comment by phil-arista** [comment]
Hi, we're working on improving this, but would you mind providing some more details? Setup, tasks run, number of nodes, etc.  Thanks!

**Comment by phil-arista** [comment]
This is fixed in the dev branch.  It's still not fast since 'show run all' is used to parse the config.  In PR https://github.com/arista-eosplus/ansible-eos/pull/88 we add a knob to control autorefresh, so the running config will only get pulled down 1x (max 2x if router bgp is created) and then all other commands will get run to configure the attributes of the bgp config.

**Comment by phil-arista** [comment]
Release Note:
This has been improved. It's still not lightning fast since 'show run all' is used to parse the config. In PR #88 we add a knob to control pyeapi's autorefresh, so the running config will only get pulled down 1x (max 2x if router bgp is created) and then all other commands will get run to configure the attributes of the bgp config.
