### ISSUE TITLE
eos_interface defaulting an interface

### ISSUE THREAD

**Issue by jedelman8** [arista-eosplus/ansible-eos#73]
Trying to default an interface and seeing this.

```
- eos_interface: name=Ethernet1 state=default connection={{ inventory_hostname }}
```

Resulting in this:

```
TASK: [eos_interface name=Ethernet1 state=default connection={{ inventory_hostname }}] *** 
failed: [leaf1] => {"failed": true}
msg: 'str' object is not callable
failed: [leaf2] => {"failed": true}
msg: 'str' object is not callable

FATAL: all hosts have already failed -- aborting
```

**Comment by phil-arista** [comment]
Hi @jedelman8 I think we have a bug here.  There is a bug in common/eos.py that is preventing the common code from calling the 'default'. The eos_interface module is also missing the default method. We're working on wrapping up a release by Friday, so I'll try and get this in that release.

**Comment by phil-arista** [comment]
Release Note:
The common/eos.py code was fixed to allow flexible support of state methods within the module.  This issue was resolved with that addition to the common code along with an added 'default' method within the module to call the interfaces API default method.  Note that state=default is not an idempotent operation.  It will run every time since the resulting state will be state=present.
